default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aulas_testes_automatizados_development

test:
  <<: *default
  database: aulas_testes_automatizados_test

production:
  <<: *default
  database: aulas_testes_automatizados_production
  username: aulas_testes_automatizados
  password: <%= ENV['AULAS_TESTES_AUTOMATIZADOS_DATABASE_PASSWORD'] %>
